// swift-tools-version: 5.7
// The swift-tools-version declares the minimum version of Swift required to build this package.
// This file is autogenerated, do not make manual changes
import PackageDescription

let package = Package(
    name: "EmbeddedWalletSDK",
    platforms: [.iOS(.v14)],
    products: [
        .library(
            name: "EmbeddedWalletSDK",
            targets: ["EmbeddedWalletSDK"]),
    ],
    dependencies: [
    ],
    targets: [
            .binaryTarget(name: "EmbeddedWalletSDK", url: "https://github.com/fireblocks/ew-ios-sdk/releases/download/1.0.7/iOS-EmbeddedWalletSDK.zip", checksum: "2cabcc4d1f6f6ce29172c952245a775b36b67b62c951aa8cae2a60dd406617b1")
    ]
)
