// swift-tools-version: 5.7
// The swift-tools-version declares the minimum version of Swift required to build this package.
// This file is autogenerated, do not make manual changes
import PackageDescription

let package = Package(
    name: "EmbeddedWalletSDK",
    platforms: [.iOS(.v14)],
    products: [
        .library(
            name: "EmbeddedWalletSDK",
            targets: ["EmbeddedWalletSDK"]),
    ],
    dependencies: [
    ],
    targets: [
            .binaryTarget(name: "EmbeddedWalletSDK", url: "https://github.com/fireblocks/ew-ios-sdk/releases/download/1.0.5/iOS-EmbeddedWalletSDK.zip", checksum: "5bbecfd45018615b215ffb3e3d163b6d58f9832edc3ea58de043d03c404d38c4")
    ]
)
