// swift-tools-version: 5.7
// The swift-tools-version declares the minimum version of Swift required to build this package.
// This file is autogenerated, do not make manual changes
import PackageDescription

let package = Package(
    name: "EmbeddedWalletSDK",
    platforms: [.iOS(.v14)],
    products: [
        .library(
            name: "EmbeddedWalletSDK",
            targets: ["EmbeddedWalletSDK"]),
    ],
    dependencies: [
    ],
    targets: [
            .binaryTarget(name: "EmbeddedWalletSDK", url: "https://github.com/fireblocks/ew-ios-sdk/releases/download/1.0.0/iOS-EmbeddedWalletSDK.zip", checksum: "b31f459ba26025f938bd73370c9a5f50190c29b1c564e015653963a320bb6efb")
    ]
)
