// swift-tools-version: 5.7
// The swift-tools-version declares the minimum version of Swift required to build this package.
// This file is autogenerated, do not make manual changes

import PackageDescription

let package = Package(
    name: "EmbeddedWalletSDK",
    platforms: [.iOS(.v14)],
    products: [
        .library(
            name: "EmbeddedWalletSDK",
            targets: ["EmbeddedWalletSDK"])
    ],
    dependencies: [
        .package(name: "FireblocksSDK",
                 url: "https://github.com/fireblocks/ncw-ios-sdk.git",
                 .upToNextMajor(from: "2.9.1"))
        ],
    targets: [
        .binaryTarget(name: "EmbeddedWalletFramework", url: "https://github.com/fireblocks/ew-ios-sdk/releases/download/0.1.0/iOS-EmbeddedWalletSDK.zip", checksum: "9a3acc86d6d70da51b8624cf7289dc8748324950345563007b772727133b0d8b"),
        .target(name: "EmbeddedWalletSDK",
                dependencies: [
                    .target(name: "EmbeddedWalletFramework"),
                    .product(name: "FireblocksSDK", package: "FireblocksSDK")
                ])

    ]

)
